# Generated by Django 3.0.3 on 2021-01-19 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogContact',
            new_name='ContactBlog',
        ),
    ]
