# Generated by Django 3.0.3 on 2021-01-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210119_2307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogContact',
        ),
    ]
