# Generated by Django 3.0.3 on 2021-01-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srn', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=40)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
