# Generated by Django 3.0.3 on 2021-01-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
