# Generated by Django 3.0.3 on 2021-11-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210120_1309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogContact',
        ),
    ]
